# Generated by Django 6.0.3 on 2026-05-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockproduct',
            options={'verbose_name': 'Связующее звено', 'verbose_name_plural': 'Связующее звено'},
        ),
    ]
