# Generated by Django 6.0.3 on 2026-05-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_stockproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='logistic.stock'),
        ),
    ]
